name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jaybakre/wallpaper-service:latest

  deploy:
    name: Deploy on Self-Hosted Server
    needs: build
    runs-on: self-hosted

    steps:
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Image
        run: docker pull jaybakre/wallpaper-service:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop wallpaper-service || true
          docker rm wallpaper-service || true

      - name: Run New Docker Container
        run: docker run -d -p 80:80 --name wallpaper-service jaybakre/wallpaper-service:latest
