name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t jaybakre/wallpaper-service:latest .
          docker tag jaybakre/wallpaper-service:latest jaybakre/wallpaper-service:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker Image
        run: |
          docker push jaybakre/wallpaper-service:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull jaybakre/wallpaper-service:latest
      - name: Stop and Remove Container
        run: docker stop wallpaper-service || true && docker rm wallpaper-service || true
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name wallpaper-service jaybakre/wallpaper-service:latest
