name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t alphagroup/wallpaper-service .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          token: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker Image
        run: docker push alphagroup/wallpaper-service:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull alphagroup/wallpaper-service:latest
      - name: Stop and Remove Container
        run: docker stop wallpaper-service || true && docker rm wallpaper-service || true
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name wallpaper-service alphagroup/wallpaper-service:latest
